apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
  template:
    metadata:
      labels:
        app: ping-pong-server
    spec:
      containers:
      - name: ping-pong
        image: <your-registry>/ping-pong-server:latest
        ports:
        - containerPort: 4433
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
spec:
  selector:
    app: ping-pong-server
  ports:
  - name: http
    port: 33
    targetPort: 4433
  type: LoadBalancer